<a href="https://colab.research.google.com/github/simran2352/suhana-/blob/main/CIE_4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

***AVERAGING METHOD***

In [ ]:
import pandas as pd
df=pd.read_csv('/content/titanic.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
import xgboost as xgb
import numpy as np
titanic = pd.read_csv('/content/titanic.csv')
features = ['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']
target = 'Survived'
titanic = titanic.dropna(subset=features + [target])
LabelEncoder = LabelEncoder()
titanic['Sex'] = LabelEncoder.fit_transform(titanic['Sex'])
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model1= LinearRegression()
model2 = RandomForestRegressor()
model3 = xgb.XGBClassifier()
model1.fit(X_train, y_train)
model2.fit(X_train, y_train)
model3.fit(X_train, y_train)
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)
final_pred = (pred1+pred2+pred3)/3.0
print("Mse:",mean_squared_error(y_test,final_pred))

Mse: 0.1581282317683963

In [15]:
print(final_pred)

[ 0.61825781  0.78093168  0.91772967  1.01727304  0.00527103  0.21046985
  0.19633634  0.71748243  0.44232956  0.46434575  1.01592111  0.92864331
  0.6447233   0.04240935  1.02903793  0.10180795  0.10552487  1.03110106
  0.12763217  0.92722683  0.3134694   0.78329837  0.83708667  0.74814508
  0.05597848  0.08043288  0.08763004  0.04472225  0.80155457  0.03247545
  0.23220437  0.36720735  0.78718108  0.02788444  0.08841869  0.23348308
  0.10604536  0.099912    0.0877259  -0.0171721   0.51517509  0.10154999
  0.96686487  0.03951121  0.25846741  0.93683735  0.90519186  0.32837454
  0.19196186  0.89993622  0.71663733  0.94906656  0.72733134  0.0393646
  0.06857199  0.84956078  0.33485531  0.05625204  0.03246126  0.01998758
  0.83522778  0.06529829  0.40822294  0.08043288  0.12774962  0.25401536
  0.66610713  1.01642781  0.09289768  0.34587873  0.08043288  0.9268916
  0.0698061   0.13699045  0.07051083  0.101106    0.12774962  0.06878481
  0.29964348  0.77270705  0.20457998  0.23429223  0.18985557  0.06936856
  0.04531157  0.40161753  0.20938545  0.01416773  0.05970679  0.15059781
  0.17223714  0.98394251  0.86637992  0.18185003  0.91815015  0.77713754
  1.01846781  0.76431167  0.12042396  0.2223071   0.93945562  0.95886767
  0.0665734   0.68445099  0.94405696  0.07894763  0.10398833  0.67126005
  0.10720975  0.8780025   0.64229333  0.05914725  0.01183563  0.25242521
  0.09380033  0.29791887  0.50428975  0.79581231  0.21238059  0.00874231
  1.02039557 -0.01207645  0.02905479  0.10398833  0.99601498  0.04290812
  0.06498861  0.96579949  0.57903217  0.52563367  0.0281905   0.0251068
  0.04384785  0.92149034  0.21262754  0.0524641   0.10289466  0.39731274
  0.03957621  0.11619093  0.02454464  0.95605923  1.00674239]